### ISSUE TITLE
Feature Request: DSL based approach to writing DMN

### ISSUE THREAD

**Issue by magick93** [DecisionToolkit/dsntk#6]
DMN models provide an excellent way to visual describe decision logic. 

However, when it comes to the DX of writing and reviewing changes in common git based workflows, it is not as good as code based approach. 

The DMN ecosystem is, in general, lacking a good code first approach to writing DMN models. 

The only contender I've found is https://github.com/powerflows/powerflows-dmn. However this has not had any updates for a few years. And, lacks the deliciousness of rust.

I'd be interested in hearing yours, and others, thoughts on this.

**Comment by ghost** [comment]
Hi @magick93!

This idea is simply great. I like the concept used in powerflows. Do you have already some vision in what language such a model would be built? Pure Rust? Some dedicated model file? Similar like powerflows in multiple formats?
Let me know what you think :-)

**Comment by ghost** [comment]
Postponed to near future...

**Comment by magick93** [comment]
Glad to hear you like it!

I see DMN (and related standards like BPMN) as an incredibly powerful, well designed, but cumbersome due to the lack of text based authoring

>  Do you have already some vision in what language such a model would be built? Pure Rust? Some dedicated model file? Similar like powerflows in multiple formats?

To have the most general acceptance I would suggest a json based language. Perhaps this could be consumed (validated and integrated) via a rust based cli utility. This would allow it to be integrated into an IDE too. Perhaps use LSP.

**Comment by ghost** [comment]
Ok. I am reopening this issue. Let us work on it.

## Vision
The general idea is to create a DSL for text based authoring of DMN models. The output from "compiling/interpreting" such a language would be DMN compliant model, that will be serialized to XML as it states in the DMN specification.
Preparing [LSP](https://langserver.org/) will make IDE integration easier. This way everyone will be able to create/update/govern decision models using just the text editor and Git. There will be no need to use seprcialized XML editor or expensive visual tool for drawing boxes. As DSNTK (in some extent) already allows to export any DMN model to HTML (that can be later converted to PDF) then the visualisation of text-authored DMN model is already there.

@magick93 agreed? Am I missing anything?

**Comment by magick93** [comment]
Agree! Sounds great!

**Comment by magick93** [comment]
FYI - the use of md for dmn tables looks interesting - https://github.com/smucclaw/dmnmd

**Comment by DariuszDepta** [comment]
Hi @magick93! In this PR #89, evaluating Markdown decision tables is on the way.
If you would like to help in any way (like testing edge cases) then let me know.
Any help is greatly appreciated!

**Comment by DariuszDepta** [comment]
@magick93 Released version 0.2.0 with support for Markdown decision tables.
Examples: https://github.com/DecisionToolkit/dsntk-rs/tree/main/examples/src/decision_tables

**Comment by magick93** [comment]
@DariuszDepta - this looks _so_ good!

Really nice work!

**Comment by DariuszDepta** [comment]
@magick93 There is a first approach to quasi-DSL in this PR: #101
The model file could look like this:

```
.NAMESPACE https://decision-toolkit.org
.NAME compliance-level-2-test-0004
.ID _3859fe63-c8a7-4fc7-8a10-f27830e9d2ac
.VERSION https://www.omg.org/spec/DMN/20191111/MODEL/
.DECISION
    .NAME Approval Status
    .ID _3b2953a3-745f-4d2e-b55d-75c8c5ae653c
    .VARIABLE
        .NAME Approval Status
        .ID _8ee5dd22-4857-4ccf-97dd-b3f87cabf05f
        .TYPE-REF string
    .INFORMATION-REQUIREMENT
        .ID _c565bfc1-53ae-4e25-ad35-b26767a9b1d9
        .REQUIRED-INPUT
            .HREF #_5a4bdb64-f0ef-4978-9e03-6f1ae64a1f17
    .INFORMATION-REQUIREMENT
        .ID _ac23f1ad-562f-47e9-a369-d9cc01f8b415
        .REQUIRED-INPUT
            .HREF #_41effb45-b3c4-46ac-b1da-122b3e428a98
    .INFORMATION-REQUIREMENT
        .ID _ae239e86-d326-4513-a01b-24e18269de29
        .REQUIRED-INPUT
            .HREF #_8ff18665-84e9-49f2-a8df-8981b1844549
    .DECISION-TABLE
        ┌───┬───────────┬────────────────────────┬──────────────╥────────────────────────┐
        │ U │    Age    │      RiskCategory      │ isAffordable ║     Approval Status    │
        │   ├───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │   │ [10..120] │"High", "Low", "Medium" │ false, true  ║ "Approved", "Declined" │
        ╞═══╪═══════════╪════════════════════════╪══════════════╬════════════════════════╡
        │ 1 │   >=18    │    "Medium", "Low"     │     true     ║       "Approved"       │
        ├───┼───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │ 2 │    <18    │    "Medium", "Low"     │     true     ║       "Declined"       │
        ├───┼───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │ 3 │     -     │         "High"         │     true     ║       "Declined"       │
        ├───┼───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │ 4 │     -     │           -            │    false     ║       "Declined"       │
        └───┴───────────┴────────────────────────┴──────────────╨────────────────────────┘
        .ID _73ec5c56-978c-45ee-a0b7-9585fb48008e
.INPUT-DATA
    .NAME Age
    .ID _41effb45-b3c4-46ac-b1da-122b3e428a98
    .VARIABLE
        .NAME Age
        .ID _e073557f-c20f-42e4-ba1a-b98c15daec50
        .TYPE-REF number
.INPUT-DATA
    .NAME RiskCategory
    .ID _5a4bdb64-f0ef-4978-9e03-6f1ae64a1f17
    .VARIABLE
        .NAME RiskCategory
        .ID _7c9ecedf-0010-488d-9b93-122520ddaab5
        .TYPE-REF string
.INPUT-DATA
    .NAME isAffordable
    .ID _8ff18665-84e9-49f2-a8df-8981b1844549
    .VARIABLE
        .NAME isAffordable
        .ID _2af698d7-017a-40b9-bea5-94ee748e4a30
        .TYPE-REF boolean

```
This is an equivalent of this model:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions namespace="https://decision-toolkit.org"
             name="compliance-level-2-test-0004"
             id="_3859fe63-c8a7-4fc7-8a10-f27830e9d2ac"
             xmlns="https://www.omg.org/spec/DMN/20191111/MODEL/"
             xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/"
             xmlns:dmndi="https://www.omg.org/spec/DMN/20191111/DMNDI/"
             xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/">
    <decision name="Approval Status" id="_3b2953a3-745f-4d2e-b55d-75c8c5ae653c">
        <variable typeRef="string" name="Approval Status" id="_8ee5dd22-4857-4ccf-97dd-b3f87cabf05f"/>
        <informationRequirement id="_c565bfc1-53ae-4e25-ad35-b26767a9b1d9">
            <requiredInput href="#_5a4bdb64-f0ef-4978-9e03-6f1ae64a1f17"/>
        </informationRequirement>
        <informationRequirement id="_ac23f1ad-562f-47e9-a369-d9cc01f8b415">
            <requiredInput href="#_41effb45-b3c4-46ac-b1da-122b3e428a98"/>
        </informationRequirement>
        <informationRequirement id="_ae239e86-d326-4513-a01b-24e18269de29">
            <requiredInput href="#_8ff18665-84e9-49f2-a8df-8981b1844549"/>
        </informationRequirement>
        <decisionTable outputLabel="Approval Status" id="_73ec5c56-978c-45ee-a0b7-9585fb48008e">
            <input id="_bf7fc56f-ea82-464e-a541-f3221dc07e78" label="Age">
                <inputExpression typeRef="number">
                    <text>Age</text>
                </inputExpression>
                <inputValues>
                    <text>[10..120]</text>
                </inputValues>
            </input>
            <input id="_bb73bf86-b399-490a-a635-c6f2c04ff75d" label="RiskCategory">
                <inputExpression typeRef="string">
                    <text>RiskCategory</text>
                </inputExpression>
                <inputValues>
                    <text>"High", "Low", "Medium"</text>
                </inputValues>
            </input>
            <input id="_af5e5c2a-5124-4277-9409-d07421dcb5a4" label="isAffordable">
                <inputExpression typeRef="boolean">
                    <text>isAffordable</text>
                </inputExpression>
                <inputValues>
                    <text>false, true</text>
                </inputValues>
            </input>
            <output id="_bffba7a1-f0a2-4679-b6e2-50e27bb27968" name="Approval Status">
                <outputValues>
                    <text>"Approved", "Declined"</text>
                </outputValues>
            </output>
            <rule id="_7f03803d-2636-40ab-8346-7fd7f38ab695">
                <inputEntry id="_7f03803d-2636-40ab-8346-7fd7f38ab695-0">
                    <text>&gt;=18</text>
                </inputEntry>
                <inputEntry id="_7f03803d-2636-40ab-8346-7fd7f38ab695-1">
                    <text>"Medium", "Low"</text>
                </inputEntry>
                <inputEntry id="_7f03803d-2636-40ab-8346-7fd7f38ab695-2">
                    <text>true</text>
                </inputEntry>
                <outputEntry id="_7f03803d-2636-40ab-8346-7fd7f38ab695-3">
                    <text>"Approved"</text>
                </outputEntry>
            </rule>
            <rule id="_887acecd-40fc-42da-9443-eeba476f5516">
                <inputEntry id="_887acecd-40fc-42da-9443-eeba476f5516-0">
                    <text>&lt;18</text>
                </inputEntry>
                <inputEntry id="_887acecd-40fc-42da-9443-eeba476f5516-1">
                    <text>"Medium", "Low"</text>
                </inputEntry>
                <inputEntry id="_887acecd-40fc-42da-9443-eeba476f5516-2">
                    <text>true</text>
                </inputEntry>
                <outputEntry id="_887acecd-40fc-42da-9443-eeba476f5516-3">
                    <text>"Declined"</text>
                </outputEntry>
            </rule>
            <rule id="_18058414-a571-4375-991f-77b9ea7fc699">
                <inputEntry id="_18058414-a571-4375-991f-77b9ea7fc699-0">
                    <text>-</text>
                </inputEntry>
                <inputEntry id="_18058414-a571-4375-991f-77b9ea7fc699-1">
                    <text>"High"</text>
                </inputEntry>
                <inputEntry id="_18058414-a571-4375-991f-77b9ea7fc699-2">
                    <text>true</text>
                </inputEntry>
                <outputEntry id="_18058414-a571-4375-991f-77b9ea7fc699-3">
                    <text>"Declined"</text>
                </outputEntry>
            </rule>
            <rule id="_ede3e62a-43f3-49d3-90a4-ffaf1f698f54">
                <inputEntry id="_ede3e62a-43f3-49d3-90a4-ffaf1f698f54-0">
                    <text>-</text>
                </inputEntry>
                <inputEntry id="_ede3e62a-43f3-49d3-90a4-ffaf1f698f54-1">
                    <text>-</text>
                </inputEntry>
                <inputEntry id="_ede3e62a-43f3-49d3-90a4-ffaf1f698f54-2">
                    <text>false</text>
                </inputEntry>
                <outputEntry id="_ede3e62a-43f3-49d3-90a4-ffaf1f698f54-3">
                    <text>"Declined"</text>
                </outputEntry>
            </rule>
        </decisionTable>
    </decision>
    <inputData name="Age" id="_41effb45-b3c4-46ac-b1da-122b3e428a98">
        <variable typeRef="number" name="Age" id="_e073557f-c20f-42e4-ba1a-b98c15daec50"/>
    </inputData>
    <inputData name="RiskCategory" id="_5a4bdb64-f0ef-4978-9e03-6f1ae64a1f17">
        <variable typeRef="string" name="RiskCategory" id="_7c9ecedf-0010-488d-9b93-122520ddaab5"/>
    </inputData>
    <inputData name="isAffordable" id="_8ff18665-84e9-49f2-a8df-8981b1844549">
        <variable typeRef="boolean" name="isAffordable" id="_2af698d7-017a-40b9-bea5-94ee748e4a30"/>
    </inputData>
</definitions>
```

**Comment by DariuszDepta** [comment]
@magick93 The IDML (Indented Delimiter Markup Language) looks little bit awkward in the exanple above, because there is no syntax highlighting on GitHub. But there is a power in this format. You can mix a tree structure with any textual content. It means that in place of Unicode decision table you can also place Markup decision table. Some other DMN structures can also be placed in textual form. Each key (with delimiter prefix - like a dot) is placed in separate line, so any change is easily readable in Git. There is also less stuff than in XML and quite similar to YAML. **But the power is in mixing the tree structure with ANY textual content.**.
Let me know your opinion on this idea!

**Comment by magick93** [comment]
Thanks @DariuszDepta 

> There is also less stuff than in XML and quite similar to YAML. But the power is in mixing the tree structure with ANY textual content..


Its definitely an improvement on the xml.

It is almost identical to yaml, and it should be possible to include raw text. Here is my attempt at the same, in yaml. 

For raw text you can use the `DECISION-TABLE: |`. 

```yaml
NAMESPACE: https://decision-toolkitorg
NAME: compliance-level-2-test-0004
ID: _3859fe63-c8a7-4fc7-8a10-f27830e9d2ac
VERSION: https://wwwomgorg/spec/DMN/20191111/MODEL/
DECISION:
    NAME: Approval Status
    ID: _3b2953a3-745f-4d2e-b55d-75c8c5ae653c
    VARIABLE:
        NAME: Approval Status
        ID: _8ee5dd22-4857-4ccf-97dd-b3f87cabf05f
        TYPE-REF: string
    INFORMATION-REQUIREMENT:
      - ID: _c565bfc1-53ae-4e25-ad35-b26767a9b1d9
        REQUIRED-INPUT:
        REF: '#_5a4bdb64-f0ef-4978-9e03-6f1ae64a1f17'
    
      - ID: _ac23f1ad-562f-47e9-a369-d9cc01f8b415
        REQUIRED-INPUT:
        HREF: '#_41effb45-b3c4-46ac-b1da-122b3e428a98'

      - ID: _ae239e86-d326-4513-a01b-24e18269de29
        REQUIRED-INPUT:
        HREF: '#_8ff18665-84e9-49f2-a8df-8981b1844549'
    DECISION-TABLE: |
        ┌───┬───────────┬────────────────────────┬──────────────╥────────────────────────┐
        │ U │    Age    │      RiskCategory      │ isAffordable ║     Approval Status    │
        │   ├───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │   │ [10120] │"High", "Low", "Medium" │ false, true  ║ "Approved", "Declined" │
        ╞═══╪═══════════╪════════════════════════╪══════════════╬════════════════════════╡
        │ 1 │   >=18    │    "Medium", "Low"     │     true     ║       "Approved"       │
        ├───┼───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │ 2 │    <18    │    "Medium", "Low"     │     true     ║       "Declined"       │
        ├───┼───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │ 3 │     -     │         "High"         │     true     ║       "Declined"       │
        ├───┼───────────┼────────────────────────┼──────────────╫────────────────────────┤
        │ 4 │     -     │           -            │    false     ║       "Declined"       │
        └───┴───────────┴────────────────────────┴──────────────╨────────────────────────┘
      - ID: _73ec5c56-978c-45ee-a0b7-9585fb48008e
INPUT-DATA:
  - ID: _41effb45-b3c4-46ac-b1da-122b3e428a98  
    NAME: Age    
    VARIABLE:
        NAME:  Age
        ID: _e073557f-c20f-42e4-ba1a-b98c15daec50
        TYPE-REF: number
  - ID: _5a4bdb64-f0ef-4978-9e03-6f1ae64a1f17  
    NAME: RiskCategory
    VARIABLE:
        NAME: RiskCategory
        ID: _7c9ecedf-0010-488d-9b93-122520ddaab5
        TYPE-REF: string
  - ID: _8ff18665-84e9-49f2-a8df-8981b1844549
    NAME: isAffordable
    VARIABLE:
        NAME isAffordable
        ID _2af698d7-017a-40b9-bea5-94ee748e4a30
        TYPE-REF boolean
```

I think the benefit of yaml, similar to markdown, is wider adoption.

# Tree

But, yes, tree structure in yaml may not be possible. Not sure. But a clean way to solve this would be to use a combination of `href` and the filesystem to link files.
